baseURL = "https://zxjx2681.com/"
languageCode = "zh-cn"
title = "我的博客"
theme = "comfy"
pagination.pagerSize = 10

[params]
  description = "记录技术与生活"
  bio = "记录技术与生活"

  [params.social]
    # 取消注释并填写你的社交账号
    youtube = "你的频道名"
    twitter = "你的用户名"
    bilibili = "你的UID"
    telegram = "@ZXJX2681"
    github = "你的用户名"
    email = "zhang70424@gmail.com"

[taxonomies]
  category = "categories"
  tag = "tags"

[[menu.main]]
  name = "首页"
  url = "/"
  weight = 1

[[menu.main]]
  name = "归档"
  url = "/archives/"
  weight = 2

[markup]
  [markup.highlight]
    style = "dracula"
    lineNos = false
    codeFences = true
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[services]
  [services.rss]
    limit = 20
